disabled_rules: # rule identifiers to exclude from running
  - force_try
  - leading_whitespace
  - line_length
  - operator_whitespace
  - return_arrow_whitespace
  - trailing_semicolon
  - trailing_whitespace
  - valid_docs
  - variable_name
  - identifier_name
  - variable_name_min_length
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - fastlane
  - XLProjectName/Helpers/R-Swift/R.generated.swift
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 230
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 30 # warning
  - 40 # error
variable_name_min_length:
  - 2 # warning
  - 1 # error
